export enum StatusEnum {
  ABERTO = 'ABERTO',
  CANCELADO = 'CANCELADO',
  CONFIRMADO = 'CONFIRMADO',
  EM_EXECUCAO = 'EM EXECUÇÃO',
  CONCLUIDO = 'CONCLUIDO',
  RECEBIDO = 'RECEBIDO',
  PAGO = 'PAGO'

}
